### PR TITLE
Fixed bug in availability checking

### LINKED ISSUE #124: TASK: check if waitinglist if full before registering

### PR DESCRIPTION
**Pull request by Kori-Kozicki**
Very small but very important. This line fixes it and makes sure the redraw button shows up when its actually possible to redraw

### CODE REVIEW

File: app/src/main/java/com/example/pygmyhippo/organizer/EventFragment.java [hunk 1]
```diff
@@ -295,16 +295,14 @@ private void populateAllFields() {
         eventAboutDescriptionView.setText(event.getDescription());
 
         // If the event is closed, then change the style of the draw button (and there are no available spots)
-        if (!event.hasAvailability()) {
-            if (event.getEventStatus().value.equals("cancelled")) {
+        if (event.getEventStatus().value.equals("cancelled")) {
```
Comment (katzhong) [inline app/src/main/java/com/example/pygmyhippo/organizer/EventFragment.java:298]: NIT: instead of using the 'cancelled` string, you could do something like `Event.EventStatus.cancelled`

**Review by katzhong — APPROVED** [review]
looks good!
